# this yaml config file goes in .themer/templates/i3/config.yaml
variables:
  theme: theme_name
  primary: magenta
  secondary: green
  tertiary: red
  special: yellow
  shading: term_trans
  fontName: terminus
  fontSize: 10
  font: "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
files:
  xresources.tpl: Xresources
  index.tpl: index.html
  i3.conf: i3.conf
  bashrc.tpl: bashrc
  bar.tpl: bar.sh
  rlb: rlb
  startpage.tpl : startpage.html
